### ISSUE TITLE
Import paths

### ISSUE THREAD

**Issue by zacksinclair** [fredmarques/go-person-server#1]
Import paths are currently prefixed with `webshield/`
Git clones by default into `go-person-server/`
Resulting in:
```
main.go:5:2: cannot find package "webshield/server" in any of:
        /usr/local/go/src/webshield/server (from $GOROOT)
        /Users/zack/Documents/GitHub/go/src/webshield/server (from $GOPATH)
```

So either:
1. paths should be prefixed with `go-person-server/' instead of `webshield`
2. rename repo to webshield

I'm only asking you tweak this so that the other devs can pull it down and run it easily when I send it over to them  :)   I got it running by just changing the folder name.

**Comment by fredmarques** [comment]
Yelp I tried to remove every webshield mentioning so this could be public. Now it should be working properly.
